### ISSUE TITLE
CCL: arguments not passed correctly to the main program

### ISSUE THREAD

**Issue by martinez** [markcox80/lisp-executable#5]
Arguments such "-b" are not passed to lisp-executable's argument handling.

They do not reach it apparently, because the arg-list goes first through CCL's own argument handling and such arguments are removed. A "--" argument is needed to prefix the arguments passed to the program.

From CCL's help text:

	Any arguments following the pseudoargument "--" are
	not processed and are available to the application as
	the value of CCL:*UNPROCESSED-COMMAND-LINE-ARGUMENTS* .

Like CLISP, I believe the output of CCL should provide a wrapping script. I have commented on this script on my previous PR, see #4

**Comment by markcox80** [comment]
Thanks @martinez. I can confirm the issue.

This command line option appears to be processed by the C function process_options in `<ccl>/lisp-kernel/pmcl-kernel.c`.

I will add a shell wrapper as suggested.

**Comment by markcox80** [comment]
Fixed in ad12292.

**Comment by martinez** [comment]
It works, thanks.
